/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.cims.model.service;
import com.cims.model.domain.*;
import com.cims.model.repository.AuditLogRepository;

import java.time.LocalDateTime;
import java.util.Collection;
/**
 *
 * @author gggob
 */
public class AuditLogServiceImpl implements AuditLogService{
    private final AuditLogRepository repository;

    public AuditLogServiceImpl(AuditLogRepository repository) {
        this.repository = repository;
    }

    @Override
    public void recordEvent(
            Equipment equipment,
            UserSession session,
            ActionType actionType,
            String notes) {

        AuditLog log = new AuditLog(
                0, // generated by Derby
                LocalDateTime.now(),
                equipment.getId(),
                equipment.getName(),
                session.getUserName(),
                session.getRole().name(),
                actionType,
                notes
        );

        repository.save(log);
    }

    @Override
    public Collection<AuditLog> getAllLogs() {
        return repository.findAll();
    }
}
